### ISSUE TITLE
Inconsistencies

### ISSUE THREAD

**Issue by rubenwardy** [rubenwardy/minetest_modding_book#85]
- [ ] " vs ' when quoting words/quotes.
- [x] British English.
- [ ] Italics/inline snippets/inverted commas. I suggest.
    * Italics for technical words.
    * Inline snippets when talking about variables, functions, or things in code.
    * Inverted commas: see 1.
- [x] Full-stops in bullet points.
- [ ] Your turn.
- [ ] Parentheses when referencing a function without saying arguments.
   I.e.: `minetest.show_formspec` vs `minetest.show_formspec()`.
         `obj:get_properties` vs `obj:get_properties()`.
- [ ] Code formatting. Stray commas, spacing, etc.

**Comment by Ezhh** [comment]
British English please.

Full stop use after every point in lists is usually compulsory when the list uses full sentences, but otherwise it doesn't have to be. I'm happy to have it used everywhere though.

I'm extremely wary of italics for technical words. Italics are usually used for emphasis, foreign words, (variables or other bits of code when there's not another option) and sometimes some other things. It's up to you in the end, but I really find it weird, and people's understanding of which words should qualify are often different as well.

**Comment by HybridDog** [comment]
>  " vs ' when quoting words/quotes.

Please always use `"` in lua code for consistency. You may use `'` when you want to quote quotes if it is really easier to read; however, usually something like `"nodename is \"" .. node.name .. "\""` is still easy to read.
